### PR TITLE
Add Circle CI

### PR DESCRIPTION
**Pull request by Deon**
I think this works. Correct me if I'm wrong @icechen1 @davepagurek

### CODE REVIEW

**Comment by yucombinator** [comment]
currently seems to fail with `There was an error while parsing your circle.yml: deployment section :machine must contain a branch or a tag`

**Comment by Deon** [comment]
Yeah, looking at that atm. They have an example like this:

```
machine:
  ruby:
    version: 1.9.3-p0-falcon
```

**Comment by Deon** [comment]
Whoops, shouldn't have nested that.

**Comment by yucombinator** [comment]
:+1:

**Pull request merged**
